# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy insta

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
vector = np.zeros((10))
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
print(vector.size)
print(vector.itemsize)
print(vector.size * vector.itemsize)

10
8
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
vector = np.zeros((10))
vector[4]=1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
vector = np.random.randint(10, 50, size=10)
print(vector)

[20 11 40 22 23 10 35 48 46 36]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
vector = vector[::-1]
print(vector)

[20 11 40 22 23 10 35 48 46 36]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
vector = np.random.randint(0, 9, size=(3,3))
print(vector)

[[7 6 0]
 [7 1 0]
 [8 4 1]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
vector = np.array([1,2,0,0,4,0])
print(vector)
print(vector.nonzero())

[1 2 0 0 4 0]
(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
vector = np.zeros((3,3))
for i in range(len(vector)):
    vector[i][i] = 1
print(vector)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
vector = np.random.rand(3,3,3)
print(vector)

[[[0.59614224 0.53720598 0.77367651]
  [0.47017743 0.90747969 0.87854077]
  [0.43452758 0.41775316 0.87870374]]

 [[0.16949865 0.98114815 0.70509456]
  [0.27980227 0.65727137 0.72052358]
  [0.5786927  0.9517716  0.88169527]]

 [[0.42692917 0.27221309 0.80233881]
  [0.15152463 0.42291162 0.67855402]
  [0.613802   0.76902701 0.97545461]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
vector = np.random.rand(10,10)
print(vector,np.min(vector),np.max(vector))

[[0.69173146 0.27456309 0.95915613 0.38888582 0.85507817 0.79379255
  0.47914114 0.62061766 0.75714135 0.15643497]
 [0.12668316 0.39898712 0.92234289 0.31077814 0.0521385  0.00582635
  0.56967661 0.05725528 0.44474858 0.16649203]
 [0.38475355 0.87839006 0.5247304  0.01293689 0.20440709 0.6881353
  0.99884686 0.26138645 0.22948849 0.45583851]
 [0.26691873 0.06824566 0.75380574 0.20746467 0.65451643 0.76928934
  0.78328466 0.44481424 0.17483194 0.46576999]
 [0.14476273 0.03633586 0.34859159 0.57751608 0.41773456 0.41715392
  0.25273158 0.80191968 0.5646993  0.18986698]
 [0.32870794 0.28134381 0.72223599 0.86266504 0.74001608 0.1690129
  0.59191951 0.94190917 0.11697749 0.25581836]
 [0.36772581 0.03196938 0.49028366 0.41896963 0.86503902 0.28799327
  0.54251084 0.08852257 0.44677732 0.32565356]
 [0.92005706 0.5074042  0.83039715 0.03557461 0.64435202 0.95742658
  0.62292977 0.21601425 0.11336703 0.95143458]
 [0.82415436 0.32782342 0.79680116 0.23115902 0.53917556 0.03529241
  0.58582493 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
vector = np.random.rand(30)
print(np.mean(vector))

0.4758564674506859


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
vector = np.ones((5,5))
vector[1:-1,1:-1] = 0
print((vector))

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [21]:
vector = np.pad(vector, pad_width=1, constant_values=0)
print(vector)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [22]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [33]:
vector = np.zeros((5,5))
for i in range(len(vector)):
    for j in range(len(vector[i])):
        if i > j:
            vector[i][j] = np.random.randint(1, 5)
print(vector)

[[0. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0.]
 [3. 4. 0. 0. 0.]
 [3. 1. 4. 0. 0.]
 [3. 3. 3. 2. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [35]:
vector = np.zeros((8,8))
for i in range(len(vector)):
    for j in range(len(vector[i])):
        if (i + j)%2==0:
            vector[i][j] = 1
print(vector)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [25]:
vector = np.arange(6*7*8).reshape(6,7,8)
print(np.where(vector == 99))

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [36]:
vector = np.zeros((8,8))
vector[::2,::2]=1
vector[1::2,1::2]=1
print(vector)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [37]:
vector = np.random.rand(5,5)
print(vector)
print(vector.mean())
print(vector.std())
vector = (vector - vector.mean()) / vector.std()
print(vector)
print(vector.mean())
print(vector.std())

[[0.27340292 0.49857366 0.15626366 0.04036715 0.0458344 ]
 [0.25400782 0.46720612 0.70694857 0.97146919 0.26593907]
 [0.06416251 0.255878   0.30353076 0.58769792 0.57295773]
 [0.77549652 0.74954367 0.11866651 0.56574413 0.1748848 ]
 [0.22384659 0.18165212 0.77862754 0.48215483 0.91161572]]
0.41705887634954486
0.27686031689011625
[[-0.5188752   0.29442567 -0.94197398 -1.36058403 -1.34083671]
 [-0.58892895  0.1811283   1.04706121  2.00249107 -0.54583411]
 [-1.27463687 -0.58217398 -0.41005559  0.61633622  0.56309572]
 [ 1.29465159  1.20091169 -1.07777227  0.53704068 -0.87471574]
 [-0.6978692  -0.85027267  1.30596058  0.23512201  1.78630456]]
6.217248937900877e-17
1.0


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [38]:
RGBA = np.dtype([('R',np.uint8),('G',np.uint8),('B',np.uint8),('A',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['R'])
type(color)

1


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [39]:
arr_1 = np.random.random((5,3))
arr_2 = np.random.random((3,2))
print(np.dot(arr_1,arr_2))

[[1.3201427  0.54570267]
 [0.60706699 0.21581859]
 [1.48627645 0.73055662]
 [1.09300223 0.56908929]
 [1.74367978 0.8898114 ]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [40]:
arr = np.arange(10)
print(arr)
arr[3:8] *= -1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2 -3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [31]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [32]:
Z = np.arange(5)
print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(print(Z<Z>Z))

[0 1 2 3 4]
[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float) / 100000000)

nan
0
[-21.47483648]


C:\Users\Nikita\AppData\Local\Temp\ipykernel_14340\21185483.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\Nikita\AppData\Local\Temp\ipykernel_14340\21185483.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
test = np.array([32.11, 51.5, 0.112])
print(np.round(test,0))

[32. 52.  0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = [10, 30, 40]
print(np.intersect1d(array1, array2))

[10 40]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow =np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(today)
print(yesterday)
print(tomorrow)

2022-09-16
2022-09-15
2022-09-17


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
dat = np.datetime64('2016-07-01')
while dat < np.datetime64('2016-08-01'):
    print(dat)
    dat+=np.timedelta64(1,'D')


2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
# Где подвох?
A = 10
B = 5
C = ((A+B)*(-A/2))
print(C)

-75.0


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
vector = np.random.rand(10) * 10
vector_int = vector.copy()
print(vector)
for j in range(len(vector)):
    vector_int[j] = int(vector_int[j])
print(vector_int)
vector_int = vector.copy()
vector_int = vector_int - vector_int % 1
print(vector_int)
vector_int = vector.copy()
vector_int = vector_int.astype(int)
print(vector_int)
vector_int = vector.copy()
print (np.floor(vector_int))

[5.59480424 5.87377621 6.23317542 6.83087678 7.47598948 6.3981291
 0.74339249 1.38540963 2.54091457 6.18001881]
[5. 5. 6. 6. 7. 6. 0. 1. 2. 6.]
[5. 5. 6. 6. 7. 6. 0. 1. 2. 6.]
[5 5 6 6 7 6 0 1 2 6]
[5. 5. 6. 6. 7. 6. 0. 1. 2. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
vector =np.array([np.arange(5)]*5)
print(vector)

[[ 0 10  2  3  4]
 [ 0  1  2  3  4]
 [ 0  1  2  3  4]
 [ 0  1  2  3  4]
 [ 0  1  2  3  4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
    for n in range(15):
        yield n
nums = np.fromiter(generate(),dtype=float,count=-1)
print("New array:")
print(nums)

New array:
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
vector = np.random.rand(10)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
vector = np.random.rand(10)
print(vector)
vector.sort()
print(vector)


[0.07545673 0.60898582 0.47178024 0.13477958 0.27617494 0.45630045
 0.49012781 0.62367395 0.12656886 0.92886092]
[0.07545673 0.12656886 0.13477958 0.27617494 0.45630045 0.47178024
 0.49012781 0.60898582 0.62367395 0.92886092]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)