# Лабораторная работа №1
### Конечномерная оптимизация, градиентные методы
## Постановка задачи
1) Запрогать GD модификацию, выбрать персонально 2 функции из книжки или scikit.

2) Их визуализировать, реализовать sgd, sgd+LR schedule. 

3) Запрогать 1 моментный метод и 1 адаптивный. 

ДОП БАЛЛ: запрогать анимацию того как метод шагает по точкам на ландшафте (гифку например).

Два варианта: выбрать 100-1000 случ точек из функции и исп в качестве датасета или сгенерировать блобы 

In [18]:
from typing import Tuple, Mapping
import numpy as np
from matplotlib import pyplot as plt
import sklearn as skl
from sklearn import datasets
from matplotlib.animation import FuncAnimation
from IPython import display
from numpy.random import permutation

In [19]:
#набор точек
x, y = skl.datasets.make_blobs(n_samples=2, centers=None, n_features=1, random_state=0)
# приведение к одной размерности
x=np.reshape(x,y.shape)

### Фунции и классы для добавления стохастичности оптимизатору ненужные в данном случае

In [118]:
def stochastic_sample(xs, ys):
    """
        stochastic_sample: sample with replacement one x and one y
        xs: all point on the plane
        ys: all response on the plane
        
        return the one randomly selected x and y point
    """
    perm = permutation(len(xs))
    x = xs[perm[0]]
    y = ys[perm[0]]
    return x, y

class lenDataloader():
    '''бесмысленый класс для создания случайного бача из пар точек x,y созданный пока я забыл что эти точки и есть оптимизационные параметры'''
    # инициатия двухмерного датасета
    def __init__(self,x,y,batch_size: int = 1,shuffle: bool = True,drop_last: bool = False) -> None:
        self.X=x
        self.Y=y
        self.batch_size=batch_size
        self.drop_last=drop_last
        self.shuffle=shuffle
        self.batchindex=0
        self.endbatchindex=0
        self.X1=[]
        self.Y1=[]
    # отображение длины датасеета 
    def len(self) -> int:
        return len(self.X)
    # перемешивания индексов датасета если включено перемешивание иначе копируем
    def permutation(self):
        if (self.shuffle==True):
            perm = permutation(self.len)
            self.X1=[self.X[ind] for ind in perm]
            self.Y1=[self.Y[ind] for ind in perm]
        else:
            self.X1=self.X
            self.Y1=self.Y
    def ReturnPermDataset(self,indxstart:int,indxstop=None,indxstep=1):
        if indxstop==None:
            return self.X1[indxstart],self.Y1[indxstart]
        else:
            return [self.X1[indxstart:indxstop:indxstep],self.Y1[indxstart:indxstop:indxstep]]
    
    def returnBatchSet(self):
        if (self.batchindex==0):
            # инициализация доп сета для перемешивания 
            self.permutation()
            self.endbatchindex=(self.len() // self.batch_size)-1
            # если датасет не делиться на ровные батчи отбрасываем последний по флагу
            if ((self.drop_last==True) and (self.len() % self.batch_size !=0)):
                self.endbatchindex-=1
        
        if ((self.drop_last==False) and (self.len() % self.batch_size !=0)and (self.batchindex+1==self.endbatchindex)):
            batch[self.ReturnPermDataset(self.batchindex*self.batch_size, self.len())]
        else:
            batch=[self.ReturnPermDataset(self.batchindex*self.batch_size, self.batchindex*self.batch_size+self.batch_size)]
        self.batchindex+=1
        
        return batch[0],batch[1]
    def endEpoch(self):
        self.batchindex=0

# Химмельблау
$$ f(x, y) = (x^2 + y - 11)^2 + (x + y^2 - 7)^2 $$

In [20]:
#функция 1
def Himmelblau(x: np.float32, y: np.float32) -> np.float64:
    '''
    Функция Химмельблау
    
    Args:
        x(np.ndarray): Аргумент 1
        y(np.ndarray): Аргумент 2
        
    Returns:
        np.float64: Результат функции
    '''
    return (np.square(np.square(x)+y-11)+np.square(x+np.square(y)-7));

#градиент 1
def Himmelblau_Grad(x: np.ndarray, y: np.ndarray) -> np.float64:
    return np.array([(4*x*(np.square(x)+y-11)+2*(x+np.square(y)-7)), (2*(np.square(x)+y-11)+4*y*(x+np.square(y)-7))]);

Himmelblau(2, 3), Himmelblau_Grad(2, 3)

(32, array([-24,  40]))

## Самая простейшая функция для оптимизации по 2 параметрам
$$ f(x, y) = x^2  +  y^2  $$

In [21]:
from symbol import yield_stmt


def mu_func(x: np.float32, y: np.float32) -> np.float64:
    '''
    Функция Химмельблау
    
    Args:
        x(np.ndarray): Аргумент 1
        y(np.ndarray): Аргумент 2
        
    Returns:
        np.float64: Результат функции
    '''
    return x**2+y**2;

#градиент 1
def mu_func_Grad(x: np.ndarray, y: np.ndarray) -> np.float64:
    return np.array([2*x, 2*y]);


C:\Users\pacha\AppData\Local\Temp\ipykernel_17716\1950936567.py:1: DeprecationWarning: The symbol module is deprecated and will be removed in future versions of Python
  from symbol import yield_stmt


## Функция Комрика
$$ f(x, y) = sin(x + y)+(x - y)^2 - 1.5x + 2.5y +1 $$

In [22]:
#функция 1
def McCormick(x: np.float32, y: np.float32) -> np.float64:
    '''
    Функция Комрика
    
    Args:
        x(np.ndarray): Аргумент 1
        y(np.ndarray): Аргумент 2с
        
    Returns:
        np.float64: Результат функции
    '''
    return np.sin(x + y)+np.square(x - y)-1.5*x+2.5*y+1;

#градиент 1
def McCormick_Grad(x: np.ndarray, y: np.ndarray) -> np.float64:
    return np.array([np.cos(x+y)+2*(x-y)-1.5, np.cos(x+y)-2*(x-y)+2.5]);

McCormick(2.5, 3.4), McCormick_Grad(2.5, 3.4)

(6.186123335169764, array([-2.37252157,  5.22747843]))

## Градиентный спуск (+ Learning Rate Schedule)

In [23]:
def my_GD_LRS(f: Mapping, df: Mapping, x: np.ndarray, y: np.ndarray, lr: float = 0.01,
          Epoch: int = 100, lre: int = 7, g: float = 0.1) -> Tuple [np.ndarray, np.ndarray, np.float32]:
    '''
    Моя простейшая реализация градиентного спуска + Learning Rate Schedule.
    
    Args:
        f (Mapping): Функционал для оптимизации
        df (Mapping): Градиент оптимизирующего функционала
        x0 (np.ndarray): Стартовая точка 1
        y0 (np.ndarray): Стартовая точка 2
        lr (float): Скорость обучения. Default=0,01.
        T (int): Количество итераций.
        lre (int): Через сколько эпох мы уменьшим lr. Default = 7.
        g (float): Коэфициент уменьшения lr [0,1). Default = 0.1
    
    Returns:
        Tuple [np.ndarray, np.float32]: (x_optimal, f(x_optimal)).
    
    '''

    for i in range(Epoch):
        if ((i%lre)==0):
            lr *= g
        n=df(x, y)
        x = x - lr*n[0]
        y = y - lr*n[1]
        
    return x, y, f(x, y)
    

In [25]:
my_GD_LRS(Himmelblau,Himmelblau_Grad,x,y,lr=0.1,lre=20)

(array([-2.80511807,  2.99997802]),
 array([3.13131252, 2.00005305]),
 array([9.70193205e-15, 4.23992343e-08]))

## GD+LRS + Momentum

In [26]:
def my_GD_LRS_mom(f: Mapping, df: Mapping, x: np.ndarray, y: np.ndarray, lr: float = 0.1,
          Epoch: int = 100, lre: int = 7, g: float = 0.1, momentum: float = 0.9) -> Tuple [np.ndarray, np.ndarray, np.float32]:
    '''
    Моя простейшая реализация градиентного спуска + Learning Rate Schedule + Momentum.
    
    Args:
        f (Mapping): Функционал для оптимизации
        df (Mapping): Градиент оптимизирующего функционала
        x0 (np.ndarray): Стартовая точка 1
        y0 (np.ndarray): Стартовая точка 2
        lr (float): Скорость обучения. Default=0,01.
        T (int): Количество итераций.
        lre (int): Через сколько эпох мы уменьшим lr. Default = 7.
        g (float): Коэфициент уменьшения lr [0,1). Default = 0.1
        momentum(float): Коэфициент сохранения момента Default = 0.9
    
    Returns:
        Tuple [np.ndarray, np.float32]: (x_optimal, f(x_optimal)).
    
    '''
    n=np.zeros(df(x, y).shape)
    for i in range(Epoch):
        if ((i%lre)==0):
            lr *= g
        n=momentum*n-lr*(1-momentum)*df(x, y)
        x = x + n[0]
        y = y + n[1]
    return x, y, f(x, y)
    

In [27]:
my_GD_LRS_mom(Himmelblau,Himmelblau_Grad,x,y,lr=0.1,lre=20)

(array([-2.39390117, -2.89573665]),
 array([2.92455126, 3.024034  ]),
 array([6.20466678, 0.7314802 ]))

## GD+LRS + Nestorev

In [29]:
def my_GD_LRS_nest(f: Mapping, df: Mapping, x0: np.ndarray, y0: np.ndarray, lr: float = 0.01,
          Epoch: int = 100, lre: int = 7, g: float = 0.1, Nestorev: float = 0.9) -> Tuple [np.ndarray, np.ndarray, np.float32]:
    '''
    Моя простейшая реализация градиентного спуска + Learning Rate Schedule + Nestorev.
    
    Args:
        f (Mapping): Функционал для оптимизации
        df (Mapping): Градиент оптимизирующего функционала
        x0 (np.ndarray): Стартовая точка 1
        y0 (np.ndarray): Стартовая точка 2
        lr (float): Скорость обучения. Default=0,01.
        T (int): Количество итераций.
        lre (int): Через сколько эпох мы уменьшим lr. Default = 7.
        g (float): Коэфициент уменьшения lr [0,1). Default = 0.1
        Nestorev(float): Коэфициент сохранения момента памяти для последующего шага Default = 0.9
    
    Returns:
        Tuple [np.ndarray, np.float32]: (x_optimal, f(x_optimal)).
    
    '''
    x = x0;
    y = y0;
    n=np.zeros(df(x, y).shape)
    for i in range(Epoch):
        if ((i%lre)==0):
            lr *= g
        n=Nestorev*n-lr*(1-Nestorev)*df(x+Nestorev*n[0]-lr*(1-Nestorev)*df(x,y)[0], y+Nestorev*n[1]-lr*(1-Nestorev)*df(x,y)[1])
        x = x + n[0]
        y = y + n[1]
        
    return x, y, f(x, y)

In [31]:
my_GD_LRS_nest(Himmelblau,Himmelblau_Grad,x,y,lr=0.1,lre=20)

(array([-2.62756952,  2.98555422]),
 array([3.12058643, 2.24287351]),
 array([0.96340252, 1.05679203]))

## Adgard

In [32]:
def my_Adgard(f: Mapping, df: Mapping, x: np.ndarray, y: np.ndarray, lr: float = 0.01,
          Epoch: int = 100, lre: int = 7, g: float = 0.1) -> Tuple [np.ndarray, np.ndarray, np.float32]:
    '''
    Моя простейшая реализация градиентного спуска + Learning Rate Schedule + Adgard.
    
    Args:
        f (Mapping): Функционал для оптимизации
        df (Mapping): Градиент оптимизирующего функционала
        x0 (np.ndarray): Стартовая точка 1
        y0 (np.ndarray): Стартовая точка 2
        lr (float): Скорость обучения. Default=0,01.
        T (int): Количество итераций.
        lre (int): Через сколько эпох мы уменьшим lr. Default = 7.
        g (float): Коэфициент уменьшения lr [0,1). Default = 0.1
    
    Returns:
        Tuple [np.ndarray, np.float32]: (x_optimal, f(x_optimal)).
    
    '''

    for i in range(Epoch):
        if ((i%lre)==0):
            lr *= g
        
        Gadapt=df(x, y)**2
        n=lr*df(x, y)/(Gadapt+0.0000001)**0.5
        x = x - n[0]
        y = y - n[1]
        
    return x, y, f(x, y)
    

In [34]:
my_Adgard(Himmelblau,Himmelblau_Grad,x,y,lr=0.1,lre=20)

(array([-1.51427812,  5.41511271]),
 array([0.22222, 0.77778]),
 array([143.64531382, 365.81711471]))

## Adam

In [55]:
from re import M


def my_Adam(f: Mapping, df: Mapping, x: np.ndarray, y: np.ndarray, lr: float = 0.01,
          Epoch: int = 100, lre: int = 7, g: float = 0.1, momentum: float = 0.9,momentumsglaj: float = 0.9) -> Tuple [np.ndarray, np.ndarray, np.float32]:
    '''
    Моя простейшая реализация градиентного спуска + Learning Rate Schedule + Momentum.
    
    Args:
        f (Mapping): Функционал для оптимизации
        df (Mapping): Градиент оптимизирующего функционала
        x0 (np.ndarray): Стартовая точка 1
        y0 (np.ndarray): Стартовая точка 2
        lr (float): Скорость обучения. Default=0,01.
        T (int): Количество итераций.
        lre (int): Через сколько эпох мы уменьшим lr. Default = 7.
        g (float): Коэфициент уменьшения lr [0,1). Default = 0.1
        momentum (float): Коэфициент сохранения момента Default = 0.9
        momentumsglaj (float): Коэфициент сохранения момента сглаживания Default = 0.9
    
    Returns:
        Tuple [np.ndarray, np.float32]: (x_optimal, f(x_optimal)).
    
    '''
    m=np.zeros(df(x, y).shape)
    Gadapt=np.zeros((df(x, y)**2).shape)
    for i in range(Epoch):
        if ((i%lre)==0):
            lr *= g
        m=momentum*m-lr*(1-momentum)*df(x, y)
        Gadapt=momentumsglaj*Gadapt+(1-momentumsglaj)*df(x, y)**2
        # if(i<100):
            # m=m/(1-momentum)
            # Gadapt=Gadapt/(1-momentumsglaj)
        n=(lr*df(x, y)*m)/(Gadapt+0.0000001)**0.5
        # print(M,Gadapt,n)
        x = x - n[0]
        y = y - n[1]
        
    return x, y, f(x, y)

In [65]:
my_Adam(Himmelblau,Himmelblau_Grad,x,y,lr=0.1,lre=50,momentumsglaj=0.8,momentum=0.999)

(array([-1.28725926,  5.71271918]),
 array([0.00283712, 1.00646645]),
 array([155.91649523, 512.71851218]))